name: Deploy Docusaurus to GitHub Pages

on:
  workflow_dispatch:
  push:
    paths:
      - 'docs/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Docusaurus
        run: npm run build

      - name: Deploy to GitHub Pages
        env:
          GIT_USER: github-actions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx docusaurus deploy --skip-build
